#!/bin/bash

# Grabs the currently playing Spotify song's title and artist, then prints it.
# For use in my tint2 panel, displaying the current song playing.
# Inspired from https://gist.github.com/wandernauta/6800547

metadata=$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:'Metadata' | grep -Ev "^method" | grep -Eo '("(.*)")|(\b[0-9][a-zA-Z0-9.]*\b)' | sed -E '2~2 a|' | tr -d '\n' | sed -E 's/\|/\n/g'| sed -E 's/(xesam:)|(mpris:)//' | sed -E 's/^"//' | sed -E 's/"$//' | sed -E 's/"+/|/' | sed -E 's/ +/ /g' | grep --color=never -E "(title)|(album)|(artist)|(trackid)|(trackNumber)" | sort -r | sed 's/^\([^|]*\)\|/\U\1/' | sed -E 's/\|/="/' | sed -E 's/$/"/' | sed -E 's/^/SPOTIFY_/')

artist=$(echo ${metadata} | grep -oP 'SPOTIFY_ARTIST="\K[^"]+')
title=$(echo ${metadata} | grep -oP 'SPOTIFY_TITLE="\K[^"]+')

echo "$title - $artist"
